import mongoengine

class User(mongoengine.Document): #need to be a top level document
    #userID is automatically generated by the mongodb
    Name = mongoengine.StringField(required=True)
    email = mongoengine.EmailField(required=True)
    UWID = mongoengine.StringField(required=True)
    Department = mongoengine.ListField(required=True)
    Authentication_level = mongoengine.StringField(required=True)
    Is_verified = mongoengine.BooleanField(default=False)

    meta={
        'db_alias': 'core',
        'collection': 'users'
    }